import os
import sys

current_dir = os.path.dirname(os.path.abspath(__file__))
minify_root = os.path.abspath(os.path.join(current_dir, os.pardir, os.pardir))
if os.getcwd() != minify_root:
    os.chdir(minify_root)

if minify_root not in sys.path:
    sys.path.insert(0, minify_root)

# isort: split

from core import base


def main():
    config_dir = base.config_dir
    # Remove temporary files generated by script.py
    for ext in [".png", ".webm"]:
        p = os.path.join(config_dir, f"_background{ext}")
        if os.path.exists(p):
            os.remove(p)
