name: Bug report
description: Create a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for your efforts!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true
        - label: It's not a virus report. See the readme for information regarding the topic.
          required: true
        - label: I've downloaded a release from https://github.com/Egezenn/dota2-minify/releases or cloned the source.
          required: true
        - label: I can read.
          required: true

  - type: input
    id: minify-version
    attributes:
      label: Minify Version
      description: What's your Minify version?
      placeholder: 1.xx.x | 1.xx.xrcx | commit-sha
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Describe the bug along with steps to produce it (screenshots are appreciated!)
      placeholder: Bug description
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What is your operating system?
      options:
        - Windows 11
        - Windows 10
        - Windows 8.x
        - Linux
        - Other (specify)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: What is your system architecture?
      options:
        - x64 (64-bit)
        - x86 (32-bit)
        - ARM
        - Other (specify)
      default: 0
    validations:
      required: true

  - type: textarea
    id: mods
    attributes:
      label: Mods
      description: Is this related to a mod? If so, what mods were you using? Paste your `config/mods.json` file
      render: json

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Have you recieved a crashlog? If so, paste your `logs/crashlog.txt` here
