name: Deploy website

on:
  push:
    branches: [main]
    paths: ["docs/**"]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-docs:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        run: uv python install 3.13

      - name: Run symdump
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        run: uv run scripts/symdump.py

      - name: Commit and push changes
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: regenerate API symbols index"
          file_pattern: "docs/wiki/development/symbols/* docs/wiki/_sidebar.md"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy to Codeberg Pages
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          cd docs
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b pages
          git add .
          git commit -m "Deploy to Codeberg Pages"
          git push --force https://egezenn:${CODEBERG_TOKEN}@codeberg.org/egezenn/${{ github.event.repository.name }}.git pages
